DELETE FROM 'SOUP_MENU';
INSERT INTO 'SOUP_MENU' (ID, NAME) VALUES (1, 'Žiadna');
INSERT INTO 'SOUP_MENU' (ID, NAME) VALUES (2, 'Paradajková so syrom');
INSERT INTO 'SOUP_MENU' (ID, NAME) VALUES (3, 'Druhá');
