DELETE FROM 'DRESSING_MENU';
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (1, 'Žiadny');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (2, 'Caesar');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (3, 'Med Horčica');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (4, 'Blue Cheese');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (5, 'Jogurtovo Bylinkový');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (6, 'Pikant');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (7, 'Olivový olej');
INSERT INTO 'DRESSING_MENU' (ID, NAME) VALUES (8, 'Balsamico tmavé');
